# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ingresarCliente.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(329, 394)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 47, 13))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 47, 13))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 47, 13))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 180, 47, 13))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 210, 47, 13))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineID = QtGui.QLineEdit(self.centralwidget)
        self.lineID.setGeometry(QtCore.QRect(100, 30, 113, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.lineID.setFont(font)
        self.lineID.setObjectName(_fromUtf8("lineID"))
        self.lineApellido = QtGui.QLineEdit(self.centralwidget)
        self.lineApellido.setGeometry(QtCore.QRect(100, 90, 113, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.lineApellido.setFont(font)
        self.lineApellido.setObjectName(_fromUtf8("lineApellido"))
        self.lineNombre = QtGui.QLineEdit(self.centralwidget)
        self.lineNombre.setGeometry(QtCore.QRect(100, 120, 113, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.lineNombre.setFont(font)
        self.lineNombre.setObjectName(_fromUtf8("lineNombre"))
        self.lineTelefono = QtGui.QLineEdit(self.centralwidget)
        self.lineTelefono.setGeometry(QtCore.QRect(100, 180, 113, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.lineTelefono.setFont(font)
        self.lineTelefono.setObjectName(_fromUtf8("lineTelefono"))
        self.lineEmail = QtGui.QLineEdit(self.centralwidget)
        self.lineEmail.setGeometry(QtCore.QRect(100, 210, 113, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.lineEmail.setFont(font)
        self.lineEmail.setObjectName(_fromUtf8("lineEmail"))
        self.btn_Ingresar = QtGui.QPushButton(self.centralwidget)
        self.btn_Ingresar.setGeometry(QtCore.QRect(230, 210, 81, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.btn_Ingresar.setFont(font)
        self.btn_Ingresar.setObjectName(_fromUtf8("btn_Ingresar"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 250, 291, 81))
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.btn_Borrar = QtGui.QPushButton(self.centralwidget)
        self.btn_Borrar.setGeometry(QtCore.QRect(230, 340, 81, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.btn_Borrar.setFont(font)
        self.btn_Borrar.setObjectName(_fromUtf8("btn_Borrar"))
        self.lineCarpeta = QtGui.QLineEdit(self.centralwidget)
        self.lineCarpeta.setGeometry(QtCore.QRect(100, 60, 113, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.lineCarpeta.setFont(font)
        self.lineCarpeta.setObjectName(_fromUtf8("lineCarpeta"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 60, 47, 13))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineDocumento = QtGui.QLineEdit(self.centralwidget)
        self.lineDocumento.setGeometry(QtCore.QRect(100, 150, 113, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.lineDocumento.setFont(font)
        self.lineDocumento.setObjectName(_fromUtf8("lineDocumento"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 150, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.btn_Borrar, QtCore.SIGNAL(_fromUtf8("clicked()")), self.plainTextEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "ID", None))
        self.label_2.setText(_translate("MainWindow", "Apellido", None))
        self.label_3.setText(_translate("MainWindow", "Nombre", None))
        self.label_4.setText(_translate("MainWindow", "Teléfono", None))
        self.label_5.setText(_translate("MainWindow", "Email", None))
        self.btn_Ingresar.setText(_translate("MainWindow", "Ingresar", None))
        self.btn_Borrar.setText(_translate("MainWindow", "Borrar", None))
        self.label_6.setText(_translate("MainWindow", "Carpeta", None))
        self.label_7.setText(_translate("MainWindow", "Documento", None))

